### ISSUE TITLE
saveAndPreviewBase64File( ) method is not working for Android

### ISSUE THREAD

**Issue by TejendraGarge** [PolarCape/polarcape-cordova-plugin-document-handler#12]
I want to open PDF document in Android Device.
I am using polarcape cordova pugin. My App am receiving Base64 string from the Server API, and I want to open the PDF intent using **saveAndPreviewBase64File** method of the plugin to achieve this.
I have set the target as Android-23, as suggested earlier, by the plugin development team.
But it is not working.
i have taken the same example which has been published in the github portal, only put alert statements for debugging purpose.
Can someone help me in running this...

PFB code

`	function PDFBase64()
	{
		alert("PDFBase64() is called...");
		
		try
		{
		
			window.DocumentHandler.saveAndPreviewBase64File(
				function (success) {
					alert("Inside Success");
					alert(JSON.stringify(success));
				},
				function (error) {
					alert("Inside error");
					alert(JSON.stringify(error));
					
					if (error == 53) {
						console.log('No app that handles this file type.');
					}
				}, 
				
				'JVBERi0xLjMKMSAwIG9iago8PCAvVHlwZSAvQ2F0YWxvZwovT3V0bGluZXMgMiAwIFIKL1BhZ2VzIDMgMCBSID4+CmVuZG9iagoyIDAgb2JqCjw8IC9UeXBlIC9PdXRsaW5lcyAvQ291bnQgMCA+PgplbmRvYmoKMyAwIG9iago8PCAvVHlwZSAvUGFnZXMKL0tpZHMgWzYgMCBSCl0KL0NvdW50IDEKL1Jlc291cmNlcyA8PAovUHJvY1NldCA0IDAgUgovRm9udCA8PCAKL0YxIDggMCBSCj4+Cj4+Ci9NZWRpYUJveCBbMC4wMDAgMC4wMDAgNjEyLjAwMCA3OTIuMDAwXQogPj4KZW5kb2JqCjQgMCBvYmoKWy9QREYgL1RleHQgXQplbmRvYmoKNSAwIG9iago8PAovQ3JlYXRvciAoRE9NUERGKQovQ3JlYXRpb25EYXRlIChEOjIwMTUwNzIwMTMzMzIzKzAyJzAwJykKL01vZERhdGUgKEQ6MjAxNTA3MjAxMzMzMjMrMDInMDAnKQo+PgplbmRvYmoKNiAwIG9iago8PCAvVHlwZSAvUGFnZQovUGFyZW50IDMgMCBSCi9Db250ZW50cyA3IDAgUgo+PgplbmRvYmoKNyAwIG9iago8PCAvRmlsdGVyIC9GbGF0ZURlY29kZQovTGVuZ3RoIDY2ID4+CnN0cmVhbQp4nOMy0DMwMFBAJovSuZxCFIxN9AwMzRTMDS31DCxNFUJSFPTdDBWMgKIKIWkKCtEaIanFJZqxCiFeCq4hAO4PD0MKZW5kc3RyZWFtCmVuZG9iago4IDAgb2JqCjw8IC9UeXBlIC9Gb250Ci9TdWJ0eXBlIC9UeXBlMQovTmFtZSAvRjEKL0Jhc2VGb250IC9UaW1lcy1Cb2xkCi9FbmNvZGluZyAvV2luQW5zaUVuY29kaW5nCj4+CmVuZG9iagp4cmVmCjAgOQowMDAwMDAwMDAwIDY1NTM1IGYgCjAwMDAwMDAwMDggMDAwMDAgbiAKMDAwMDAwMDA3MyAwMDAwMCBuIAowMDAwMDAwMTE5IDAwMDAwIG4gCjAwMDAwMDAyNzMgMDAwMDAgbiAKMDAwMDAwMDMwMiAwMDAwMCBuIAowMDAwMDAwNDE2IDAwMDAwIG4gCjAwMDAwMDA0NzkgMDAwMDAgbiAKMDAwMDAwMDYxNiAwMDAwMCBuIAp0cmFpbGVyCjw8Ci9TaXplIDkKL1Jvb3QgMSAwIFIKL0luZm8gNSAwIFIKPj4Kc3RhcnR4cmVmCjcyNQolJUVPRgo='
				,
				'application/pdf', 
				cordova.file.externalApplicationStorageDirectory, 
				'test.pdf'
			);
		}
		catch(e)
		{
			alert("Inside catch");
			alert(JSON.stringify(e));
		}
		
	}`

**Comment by vkajtazov** [comment]
This issue is covered by #9
