### ISSUE TITLE
provider_paths.xml conflicts with other plugins.

### ISSUE THREAD

**Issue by LightMind** [PolarCape/polarcape-cordova-plugin-document-handler#17]
Hello,

When installing this plugin, cordova fails with the following error:
`
Failed to install 'polarcape-cordova-plugin-document-handler': CordovaError: Uh oh!
"[...] /platforms/android/res/xml/provider_paths.xml" already exists!
`

I found that both this plugin and `cordova-plugin-camera` use this file.
Could you please prefix the file, if possible, to avoid collisions of this kind?

best regards

**Comment by sithwarrior** [comment]
#19 Should be fixed in this pullrequest

**Comment by vkajtazov** [comment]
Great !
Thanks for your collaboration @sithwarrior.
