### ISSUE TITLE
update dependency on cordova file to latest/6.0.1

### ISSUE THREAD

**Issue by lloydmurray** [PolarCape/polarcape-cordova-plugin-document-handler#21]
package json define cordova-pungin-file  as : "cordova-plugin-file": "^4.0.0".  Can that but updated to 6.0.1. This will help the plugin mingle well with other updated plugins that depend on current releases of cordova-plugin-file

I've tested locally by changed the dependency, and it works with the examples in the README

**Comment by vkajtazov** [comment]
Hi @lloydmurray, 
Please check this pull request https://github.com/PolarCape/polarcape-cordova-plugin-document-handler/pull/22
And confirm that those are the only required changes for updating the plugin.

**Comment by lloydmurray** [comment]
that works.  I approved the change and will watch for the release.  Thanks!

**Comment by vkajtazov** [comment]
Both git and npm have new published version.
Try to install now and let me know if there is a any problem.

**Comment by lloydmurray** [comment]
updated version pulled the latest file plugin.  thanks.  One thing, though.  I'm still seeing the .10 version.  maybe npm isn't updated?

Lloyds-MacBook-Pro:pdf2 lmurray$ cordova plugins
cordova-plugin-file 6.0.1 "File"
cordova-plugin-whitelist 1.3.3 "Whitelist"
polarcape-cordova-plugin-document-handler **1.0.10** "Document Handler"

**Comment by vkajtazov** [comment]
Published new 1.0.12 version to sync package.json and plugin.xml.
