### ISSUE TITLE
Cant set title?

### ISSUE THREAD

**Issue by stuarteaton** [PolarCape/polarcape-cordova-plugin-document-handler#23]
Is there anyway to set the title of the view controller?

In Example 1:
'http://www.axmag.com/download/pdfurl-guide.pdf', 'pdf-sample');

... suggests that 'pdf-sample' would be the view controllers title?

**Comment by vkajtazov** [comment]
Hi @stuarteaton 

Our plugin does not have this functionality.
Sorry, but we are only supporting minor or critical changes.
Feel free to collaborate.
