### ISSUE TITLE
Does not work with Android 7.0

### ISSUE THREAD

**Issue by TejendraGarge** [PolarCape/polarcape-cordova-plugin-document-handler#9]
I tried in most of the devices, they are working fine, but does not work with Android 7.0.
App simply stops and user get thrown out of App.
Does it tested with OS 7.0

In my project Android manifest I have set the target as 25

`<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="25" />`

Can some one help me out in this?

**Comment by phpfs** [comment]
Hello :)

Any updates to this?

Thanks so far :)

**Comment by vaskgjuri** [comment]
Apparently a quick fix for this is described [here](https://github.com/PolarCape/polarcape-cordova-plugin-document-handler/issues/10)

**Comment by vkajtazov** [comment]
Latest version supports Android 7.0
